chore: update pre-commit with mdformat

diff --git a/.hooks/pre-commit b/.hooks/pre-commit
--- a/.hooks/pre-commit
+++ b/.hooks/pre-commit
@@ -1,5 +1,11 @@
 #!/usr/bin/env bash
 
+# md fmt
+if ! command -v mdformat &> /dev/null; then
+  printf "[pre_commit] \033[0;31merror\033[0m: \"mdformat\" not available. \n"
+  exit 1
+fi
+
 # sh fmt
 if ! command -v shfmt &> /dev/null; then
   printf "[pre_commit] \033[0;31merror\033[0m: \"shfmt\" not available. \n"
@@ -23,6 +29,17 @@ if ! command -v rustfmt &> /dev/null; then
   printf "[pre_commit] \033[0;31merror\033[0m: \"rustfmt\" not available. \n"
   exit 1
 fi
+
+# format ill-formatted md files
+problem_md_files=()
+
+for file in $(git diff --name-only --cached); do
+  if [ "${file: -3}" == ".md" ]; then
+    if mdformat "$file" &>/dev/null; then
+      problem_md_files+=("$file")
+    fi
+  fi
+done
 
 # format ill-formatted sh files
 problem_sh_files=()
@@ -68,28 +85,37 @@ for file in $(git diff --name-only --cached); do
   fi
 done
 
-if [ ${#problem_sh_files[@]} == 0 ] && [ ${#problem_nix_files[@]} == 0 ] && [ ${#problem_just_files[@]} == 0 ] && [ ${#problem_rust_files[@]} == 0 ]; then
+if [ ${#problem_md_files[@]} == 0 ] && [ ${#problem_sh_files[@]} == 0 ] && [ ${#problem_nix_files[@]} == 0 ] && [ ${#problem_just_files[@]} == 0 ] && [ ${#problem_rust_files[@]} == 0 ]; then
   # done
   printf "[pre_commit] shfmt      \033[0;32mok\033[0m \n"
   printf "[pre_commit] nix fmt    \033[0;32mok\033[0m \n"
   printf "[pre_commit] rustfmt    \033[0;32mok\033[0m \n"
+  printf "[pre_commit] mdformat   \033[0;32mok\033[0m \n"
   printf "[pre_commit] just --fmt \033[0;32mok\033[0m \n"
 else
   # reformat the files that need it and re-stage them.
+
+  if [ ${#problem_md_files[@]} != 0 ]; then
+    printf "[pre_commit] the following files were mdformat'd before commit: \n"
+    for file in "${problem_md_files[@]}"; do
+      git add "$file"
+      printf "\033[0;32m  %s\033[0m \n" "$file"
+    done
+  fi
 
   if [ ${#problem_sh_files[@]} != 0 ]; then
     printf "[pre_commit] the following files were shfmt'd before commit: \n"
     for file in "${problem_sh_files[@]}"; do
       git add "$file"
-      printf "\033[0;32m - %s\033[0m \n" "$file"
+      printf "\033[0;32m  %s\033[0m \n" "$file"
     done
-  fi  
+  fi
 
   if [ ${#problem_nix_files[@]} != 0 ]; then
     printf "[pre_commit] the following files were nix fmt'd before commit: \n"
     for file in "${problem_nix_files[@]}"; do
       git add "$file"
-      printf "\033[0;32m - %s\033[0m \n" "$file"
+      printf "\033[0;32m  %s\033[0m \n" "$file"
     done
   fi
 
@@ -97,7 +123,7 @@ else
     printf "[pre_commit] the following files were just --fmt'd before commit: \n"
     for file in "${problem_just_files[@]}"; do
       git add "$file"
-      printf "\033[0;32m - %s\033[0m \n" "$file"
+      printf "\033[0;32m  %s\033[0m \n" "$file"
     done
   fi
 
@@ -105,7 +131,7 @@ else
     printf "[pre_commit] the following files were rustfmt'd before commit: \n"
     for file in "${problem_rust_files[@]}"; do
       git add "$file"
-      printf "\033[0;32m - %s\033[0m \n" "$file"
+      printf "\033[0;32m  %s\033[0m \n" "$file"
     done
   fi
 fi
